name: Deploy Novabyte Blog UI (Generic)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      NB_SSR_API_ADDR:
        required: true
        type: string
      NB_API_ADDR:
        required: true
        type: string
      NB_ADDRESS:
        required: true
        type: string
      PORT:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true

jobs:
  build-and-deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Log .env values
        run: |
          echo "NB_SSR_API_ADDR=${{ inputs.NB_SSR_API_ADDR }}"
          echo "NB_API_ADDR=${{ inputs.NB_API_ADDR }}"
          echo "NB_ADDRESS=${{ inputs.NB_ADDRESS }}"
          echo "PORT=${{ inputs.PORT }}"

      - name: Create .env file
        run: |
          echo "NB_SSR_API_ADDR=${{ inputs.NB_SSR_API_ADDR }}" >> .env
          echo "NB_API_ADDR=${{ inputs.NB_API_ADDR }}" >> .env
          echo "NB_ADDRESS=${{ inputs.NB_ADDRESS }}" >> .env
          echo "PORT=${{ inputs.PORT }}" >> .env

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Quasar
        run: yarn global add @quasar/cli

      - name: Install Dependencies
        run: yarn install

      - name: Build Quasar SSR
        run: quasar build -m ssr

      - name: Deploy to ${{ inputs.environment }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: deploy
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

          ssh $SSH_USER@$SSH_HOST "mkdir -p /srv/www/ui"
          ssh $SSH_USER@$SSH_HOST "rm -rf /srv/www/ui/*"

          scp -r dist/ssr/* $SSH_USER@$SSH_HOST:/srv/www/ui
          scp -r .env $SSH_USER@$SSH_HOST:/srv/www/ui

          ssh $SSH_USER@$SSH_HOST "yarn --cwd /srv/www/ui install"
          ssh $SSH_USER@$SSH_HOST "sudo systemctl restart ui.service"
